### ISSUE TITLE
issue with abandoned cart plugin

### ISSUE THREAD

**Issue by Tobias-Conrad** [woothemes/woocommerce-gateway-klarna#41]
the plugin developer wrote:

supportdesk( supportdesk) Date of Support Ticket Replied on: 2016-09-15 10:35:49 ( 23 mins ago )
Profile Picture End
Support Content
Hi,
We checked the feasibility to give compatibility with Klarna Payment gateway. But, we are unable to give compatibility as we are removing the Cart Id when the Order is placed( woocommerce_checkout_order_processed hook will be triggered). In case of Klarna gateway, the hook is triggered only after getting IPN response. So, it doesn't removes the recovered cart Id and creates a new entry.
For the above reason we are unable to give compatibility with Klarna Payment gateway. Please apologize us.
Thanks.

-

### WordPress version

4.6.1

### WooCommerce version

2.4.6

### Klarna country

German

`
### WordPress Environment ###

Home URL: https://www.santegra-international.com
Site URL: https://www.santegra-international.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE_formal

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 5.6.24
PHP Post Max Size: 100 MB
PHP Time Limit: 1200
PHP Max Input Vars: 3000
cURL Version: 7.47.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (55) ###

BackupBuddy: von iThemes – 7.1.6.2
Bring Back the Get Shortlink Button: von Thorsten Frommen – 1.1.0
Cachify: von pluginkollektiv – 2.2.4
WP Comment List Builder: von Tobias B. Conrad – 3.6.2
Duplicate Menu: von Jonathan Christopher – 0.2
Duplicate Post: von Enrico Battocchi – 2.6
Easy Theme and Plugin Upgrades: von Chris Jean – 2.0.0
Envato Market: von Derek Herman – 1.0.0-RC2
Multiple Themes: von David Gewirtz – 7.1.1
WPBakery Visual Composer: von Michael M - WPBakery.com – 4.12.1
Language Fallback: von Bernhard Kau – 1.0.3
Layered Popups: von Halfdata
Inc. – 5.88

Notely: von Michael Ott – 1.3
Postman SMTP: von Jason Hendriks – 1.7.2
WooCommerce Product Filter: von Mihajlovic Nenad – 5.8.5
QuickieBar: von Phil Baylog – 1.8.3
Schema Creator by Raven: von Raven Internet Marketing Tools – 1.1.1
SearchWP Exclude UI: von Jonathan Christopher – 1.0.1
SearchWP Fuzzy Matches: von Jonathan Christopher – 1.4
SearchWP LIKE Terms: von Jonathan Christopher – 2.4.4.1
SearchWP German Stemmer: von Jonathan Christopher – 1.0.1
SearchWP Term Highlight: von Jonathan Christopher – 2.0.9
SearchWP WooCommerce Integration: von SearchWP
LLC – 1.1.10

SearchWP Xpdf Integration: von Jonathan Christopher – 1.1.1
SearchWP: von SearchWP
LLC – 2.8.4

Simple Page Tester Premium: von Simple Page Tester – 1.4.2
Simple Page Tester: von Simple Page Tester – 1.4.4
Simple Tooltips: von Justin Saad – 2.1.3
NextScripts: Social Networks Auto-Poster: von NextScripts – 3.6.10
SEO by SQUIRRLY: von calinvingan
florinmuresan
nagy.sorel – 6.2.0

Statify: von pluginkollektiv – 1.4.3
Tawk.to Live Chat: von Tawkto – 0.2.1
Timed Content: von K. Tough – 2.6
TinyMCE Advanced: von Andrew Ozz – 4.4.1
Vendidero Helper: von Vendidero – 1.1.3
WooCommerce Bulk Order Form: von Jeremiah Prummer – 2.2
WooCommerce Checkout Field Editor Pro: von ThemeHiGH – 2.5.3
WooCommerce DE Avia Themes Anpassung: von InoPlugs – 1.4
WooCommerce Dropshippers: von ArticNet LLC. – 2.7
WooCommerce Email Validation: von Hugh Lashbrooke – 2.0
WooCommerce Klarna Gateway: von WooThemes – 2.1.12
WooCommerce Germanized Pro: von Vendidero – 1.5.7
WooCommerce Germanized: von Vendidero – 1.7.1
WooCommerce Google Analytics Pro: von WooThemes / SkyVerge – 1.1.4
WooCommerce Recommendation Engine: von Lucas Stark – 3.0.2
WooCommerce Sequential Order Numbers Pro: von WooThemes / SkyVerge – 1.10.0
WooCommerce Table Rate Shipping: von WooThemes – 3.0.1
WooCommerce URL Coupons: von WooThemes / SkyVerge – 2.3.1
WooCommerce: von WooThemes – 2.6.4
WooCommerce Helper: von WooCommerce – 1.7.1
Wordpress Rankie: von Atef – 1.5.0
WP Sitemap Page: von Tony Archambeau – 1.6
WP-SpamShield: von Scott Allen – 1.9.9.2
WooCommerce & WP Email Marketing Integration: von Tobias B. Conrad – 3.5.3
WpZeroBounce V2 DEV - unlimited: von Forcespark – 2

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop-Basis: #1013 - /shop/
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /checkout/
Mein Konto: #9 - /mein-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Enfold Child
Version: 1.1-2016-05-15
Author URL: http://leupus.de
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 3.8
Parent Theme Author URL: http://www.kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: Eid not set Secret key not set Checkout URL not set
Norway: Eid not set Secret key not set Checkout URL not set
Finland: Eid not set Secret key not set Checkout URL not set
Germany: ✔
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Terms Page: ✔
`

**Comment by slobodan** [comment]
@Tobias-Conrad our plugin does not support any abandoned cart plugins, and doesn't state it supports them. There is a possibility of us adding this feature in a future release, but it is currently not on the roadmap. If you'd like to contribute to adding this feature yourself, please send a pull request to our repo - https://github.com/krokedil/woocommerce-gateway-klarna 

Closing this one, in the future please do not use GitHub issue tracker for feature requests.

**Comment by Tobias-Conrad** [comment]
Dear Dev,

More clear why i write here:

If you Change the behavior of the Trigger as described it would work with all such Plugins.

So please improve to be Easy compatible 

Thanks
