### ISSUE TITLE
Take data from logged in user into klarna checkout

### ISSUE THREAD

**Issue by Tobias-Conrad** [woothemes/woocommerce-gateway-klarna#42]
it should take the name, address, etc. from the logged in user.
so social login is working with the plugin. email address is validated.
no second entering of the user data i needed.
Data could better than the data entered during klarna checkout.

system see here:
https://github.com/woothemes/woocommerce-gateway-klarna/issues/41

**Comment by slobodan** [comment]
Not sure how social login comes into play here, but Klarna Checkout does use logged in user data, UNLESS you are in test mode (for obvious reasons - to facilitate testing various scenarios).

**Comment by Tobias-Conrad** [comment]
Social Login is with one Click, e.g.
When User is logged in to Facebook.

Much faster than Klarna.
Some customer social Login before Checkout.

I will Test if the data is taken when Klarna is in live Mode. Thanks for the hint.

Thanks
